package com.dicoding.picodiploma.movies.utils

import com.dicoding.picodiploma.movies.R
import com.dicoding.picodiploma.movies.data.source.local.entity.DataMovie
import com.dicoding.picodiploma.movies.data.source.local.entity.DataTvShow
import com.dicoding.picodiploma.movies.data.source.remote.response.MovieResponse
import com.dicoding.picodiploma.movies.data.source.remote.response.TvShowResponse

object DataDummy {

    fun generateDataMovie(): List<DataMovie> {

        val movie = ArrayList<DataMovie>()

        movie.add(DataMovie(R.drawable.poster_alita,
                "Alita: Battle Angel (2019)",
                "When Alita awakens with no memory of who she is in a future world she does not recognize, she is taken in by Ido, a compassionate doctor who realizes that somewhere in this abandoned cyborg shell is the heart and soul of a young woman with an extraordinary past.",
                "02/14/2019",
                "2h 2m",
                "Released",
                "Action, Science Fiction, Adventure",
                "6,161 Ratings"))
        movie.add(DataMovie(R.drawable.poster_aquaman,
                "Aquaman (2018)",
                "Once home to the most advanced civilization on Earth, Atlantis is now an underwater kingdom ruled by the power-hungry King Orm. With a vast army at his disposal, Orm plans to conquer the remaining oceanic people and then the surface world. Standing in his way is Arthur Curry, Orm's half-human, half-Atlantean brother and true heir to the throne.",
                "12/21/2018",
                "2h 24m",
                "Released",
                "Action, Adventure, Fantasy",
                "9,949 Ratings"))
        movie.add(DataMovie(R.drawable.poster_bohemian,
                "Bohemian Rhapsody (2018)",
                "Singer Freddie Mercury, guitarist Brian May, drummer Roger Taylor and bass guitarist John Deacon take the music world by storm when they form the rock 'n' roll band Queen in 1970. Hit songs become instant classics. When Mercury's increasingly wild lifestyle starts to spiral out of control, Queen soon faces its greatest challenge yet – finding a way to keep the band together amid the success and excess.",
                "11/02/2018",
                "2h 15m",
                "Released",
                "Music, Drama",
                "12,719 Ratings"))
        movie.add(DataMovie(R.drawable.poster_creed,
                "Creed II (2018)",
                "Between personal obligations and training for his next big fight against an opponent with ties to his family's past, Adonis Creed is up against the challenge of his life.",
                "11/21/2018",
                "2h 10m",
                "Released",
                "Drama",
                "3,560 Ratings"))
        movie.add(DataMovie(R.drawable.poster_crimes,
                "Fantastic Beasts: The Crimes of Grindelwald (2018)",
                "Gellert Grindelwald has escaped imprisonment and has begun gathering followers to his cause—elevating wizards above all non-magical beings. The only one capable of putting a stop to him is the wizard he once called his closest friend, Albus Dumbledore. However, Dumbledore will need to seek help from the wizard who had thwarted Grindelwald once before, his former student Newt Scamander, who agrees to help, unaware of the dangers that lie ahead. Lines are drawn as love and loyalty are tested, even among the truest friends and family, in an increasingly divided wizarding world.",
                "11/16/2018",
                "2h 14m",
                "Released",
                "Adventure, Fantasy, Drama",
                "7,763 Ratings"))
        movie.add(DataMovie(R.drawable.poster_glass,
                "Glass (2019)",
                "In a series of escalating encounters, former security guard David Dunn uses his supernatural abilities to track Kevin Wendell Crumb, a disturbed man who has twenty-four personalities. Meanwhile, the shadowy presence of Elijah Price emerges as an orchestrator who holds secrets critical to both men.",
                "01/18/2019",
                "2h 9m",
                "Released",
                "Thriller, Drama, Science Fiction",
                "5,921 Ratings"))
        movie.add(DataMovie(R.drawable.poster_how_to_train,
                "How to Train Your Dragon: The Hidden World (2019)",
                "As Hiccup fulfills his dream of creating a peaceful dragon utopia, Toothless’ discovery of an untamed, elusive mate draws the Night Fury away. When danger mounts at home and Hiccup’s reign as village chief is tested, both dragon and rider must make impossible decisions to save their kind.",
                "02/22/2019",
                "1h 44m",
                "Released",
                "Animation, Family, Adventure",
                "4,289 Ratings"))
        movie.add(DataMovie(R.drawable.poster_infinity_war,
                "Avengers: Infinity War (2018)",
                "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.",
                "04/27/2018",
                "2h 29m",
                "Released",
                "Adventure, Action, Science Fiction",
                "20,823 Ratings"))
        movie.add(DataMovie(R.drawable.poster_master_z,
                "Master Z: Ip Man Legacy (2018)",
                "Following his defeat by Master Ip, Cheung Tin Chi tries to make a life with his young son in Hong Kong, waiting tables at a bar that caters to expats. But it's not long before the mix of foreigners, money, and triad leaders draw him once again to the fight.",
                "12/26/2018",
                "1h 47m",
                "Released",
                "Action",
                "275 Ratings"))
        movie.add(DataMovie(R.drawable.poster_mortal_engines,
                "Mortal Engines (2018)",
                "Many thousands of years in the future, Earth’s cities roam the globe on huge wheels, devouring each other in a struggle for ever diminishing resources. On one of these massive traction cities, the old London, Tom Natsworthy has an unexpected encounter with a mysterious young woman from the wastelands who will change the course of his life forever.",
                "12/14/2018",
                "2h 9m",
                "Released",
                "Adventure, Science Fiction",
                "3,199 Ratings"))
        movie.add(DataMovie(R.drawable.poster_overlord,
                "Overlord (2018)",
                "France, June 1944. On the eve of D-Day, some American paratroopers fall behind enemy lines after their aircraft crashes while on a mission to destroy a radio tower in a small village near the beaches of Normandy. After reaching their target, the surviving paratroopers realise that, in addition to fighting the Nazi troops that patrol the village, they also must fight against something else.",
                "11/09/2018",
                "1h 50m",
                "Released",
                "Horror, War, Science Fiction",
                "1,935 Ratings"))
        movie.add(DataMovie(R.drawable.poster_ralph,
                "Ralph Breaks the Internet (2018)",
                "Video game bad guy Ralph and fellow misfit Vanellope von Schweetz must risk it all by traveling to the World Wide Web in search of a replacement part to save Vanellope's video game, Sugar Rush. In way over their heads, Ralph and Vanellope rely on the citizens of the internet — the netizens — to help navigate their way, including an entrepreneur named Yesss, who is the head algorithm and the heart and soul of trend-making site BuzzzTube.",
                "11/21/2018",
                "1h 57m",
                "Released",
                "Family, Animation, Comedy, Adventure",
                "5,289 Ratings"))
        movie.add(DataMovie(R.drawable.poster_robin_hood,
                "Robin Hood (2018)",
                "A war-hardened Crusader and his Moorish commander mount an audacious revolt against the corrupt English crown.",
                "11/21/2018",
                "1h 56m",
                "Released",
                "Adventure, Action, Thriller",
                "2,159 Ratings"))
        movie.add(DataMovie(R.drawable.poster_spiderman,
                "Spider-Man: Into the Spider-Verse (2018)",
                "Miles Morales is juggling his life between being a high school student and being a spider-man. When Wilson \"Kingpin\" Fisk uses a super collider, others from across the Spider-Verse are transported to this dimension.",
                "12/14/2018",
                "1h 57m",
                "Released",
                "Action, Adventure, Animation, Science Fiction, Comedy",
                "8,876 Ratings"))
        movie.add(DataMovie(R.drawable.poster_t34,
                "T-34 (2018)",
                "In 1944, a courageous group of Russian soldiers managed to escape from German captivity in a half-destroyed legendary T-34 tank. Those were the times of unforgettable bravery, fierce fighting, unbreakable love, and legendary miracles.",
                "01/01/2019",
                "2h 19m",
                "Released",
                "War, Action, Drama, History",
                "496 Ratings"))

        return movie
    }

    fun generateDataTvShow(): List<DataTvShow> {

        val tvShow = ArrayList<DataTvShow>()

        tvShow.add(DataTvShow(R.drawable.poster_arrow,
                "Arrow (2012)",
                "Spoiled billionaire playboy Oliver Queen is missing and presumed dead when his yacht is lost at sea. He returns five years later a changed man, determined to clean up the city as a hooded vigilante armed with a bow.",
                "October 10, 2012",
                "42m",
                "Ended",
                "Crime, Drama, Mystery, Action & Adventure",
                "4,288 Ratings"))
        tvShow.add(DataTvShow(R.drawable.poster_doom_patrol,
                "Doom Patrol (2019)",
                "The Doom Patrol’s members each suffered horrible accidents that gave them superhuman abilities — but also left them scarred and disfigured. Traumatized and downtrodden, the team found purpose through The Chief, who brought them together to investigate the weirdest phenomena in existence — and to protect Earth from what they find.",
                "February 15, 2019",
                "49m",
                "Returning Series",
                "Sci-Fi & Fantasy, Action & Adventure, Comedy",
                "747 Ratings"))
        tvShow.add(DataTvShow(R.drawable.poster_dragon_ball,
                "Dragon Ball (1986)",
                "Long ago in the mountains, a fighting master known as Gohan discovered a strange boy whom he named Goku. Gohan raised him and trained Goku in martial arts until he died. The young and very strong boy was on his own, but easily managed. Then one day, Goku met a teenage girl named Bulma, whose search for the mystical Dragon Balls brought her to Goku's home. Together, they set off to find all seven and to grant her wish.",
                "February 26, 1986",
                "25m",
                "Ended",
                "Comedy, Sci-Fi & Fantasy, Animation, Action & Adventure",
                "1,567 Ratings"))
        tvShow.add(DataTvShow(R.drawable.poster_family_guy,
                "Family Guy (1999)",
                "Sick, twisted, politically incorrect and Freakin' Sweet animated series featuring the adventures of the dysfunctional Griffin family. Bumbling Peter and long-suffering Lois have three kids. Stewie (a brilliant but sadistic baby bent on killing his mother and taking over the world), Meg (the oldest, and is the most unpopular girl in town) and Chris (the middle kid, he's not very bright but has a passion for movies). The final member of the family is Brian - a talking dog and much more than a pet, he keeps Stewie in check whilst sipping Martinis and sorting through his own life issues.",
                "January 31, 1999",
                "22m",
                "Returning Series",
                "Animation, Comedy",
                "2,554 Ratings"))
        tvShow.add(DataTvShow(R.drawable.poster_flash,
                "The Flash (2014)",
                "After a particle accelerator causes a freak storm, CSI Investigator Barry Allen is struck by lightning and falls into a coma. Months later he awakens with the power of super speed, granting him the ability to move through Central City like an unseen guardian angel. Though initially excited by his newfound powers, Barry is shocked to discover he is not the only \"meta-human\" who was created in the wake of the accelerator explosion -- and not everyone is using their new powers for good. Barry partners with S.T.A.R. Labs and dedicates his life to protect the innocent. For now, only a few close friends and associates know that Barry is literally the fastest man alive, but it won't be long before the world learns what Barry Allen has become...The Flash.",
                "October 7, 2014",
                "44m",
                "Returning Series",
                "Drama, Sci-Fi & Fantasy",
                "6,611 Ratings"))
        tvShow.add(DataTvShow(R.drawable.poster_gotham,
                "Gotham (2014)",
                "Everyone knows the name Commissioner Gordon. He is one of the crime world's greatest foes, a man whose reputation is synonymous with law and order. But what is known of Gordon's story and his rise from rookie detective to Police Commissioner? What did it take to navigate the multiple layers of corruption that secretly ruled Gotham City, the spawning ground of the world's most iconic villains? And what circumstances created them – the larger-than-life personas who would become Catwoman, The Penguin, The Riddler, Two-Face and The Joker?",
                "September 22, 2014",
                "43m",
                "Ended",
                "Drama, Fantasy, Crime",
                "2,097 Ratings"))
        tvShow.add(DataTvShow(R.drawable.poster_grey_anatomy,
                "Grey's Anatomy (2005)",
                "Follows the personal and professional lives of a group of doctors at Seattle’s Grey Sloan Memorial Hospital.",
                "March 27, 2005",
                "43m",
                "Returning Series",
                "Drama",
                "5,080 Ratings"))
        tvShow.add(DataTvShow(R.drawable.poster_hanna,
                "Hanna (2019)",
                "This thriller and coming-of-age drama follows the journey of an extraordinary young girl as she evades the relentless pursuit of an off-book CIA agent and tries to unearth the truth behind who she is. Based on the 2011 Joe Wright film.",
                "March 28, 2019",
                "50m",
                "Returning Series",
                "Action & Adventure, Drama",
                "423 Ratings"))
        tvShow.add(DataTvShow(R.drawable.poster_iron_fist,
                "Marvel's Iron Fist (2017)",
                "Danny Rand resurfaces 15 years after being presumed dead. Now, with the power of the Iron Fist, he seeks to reclaim his past and fulfill his destiny.",
                "March 17, 2017",
                "55m",
                "Canceled",
                "Action & Adventure, Drama, Sci-Fi & Fantasy",
                "1,386 Ratings"))
        tvShow.add(DataTvShow(R.drawable.poster_ncis,
                "NCIS (2003)",
                "From murder and espionage to terrorism and stolen submarines, a team of special agents investigates any crime that has a shred of evidence connected to Navy and Marine Corps personnel, regardless of rank or position.",
                "September 23, 2003",
                "45m",
                "Returning Series",
                "Crime, Action & Adventure, Drama",
                "1,341 Ratings"))
        tvShow.add(DataTvShow(R.drawable.poster_riverdale,
                "Riverdale (2017)",
                "Set in the present, the series offers a bold, subversive take on Archie, Betty, Veronica and their friends, exploring the surreality of small-town life, the darkness and weirdness bubbling beneath Riverdale’s wholesome facade.",
                "January 26, 2017",
                "45m",
                "Returning Series",
                "Mystery, Drama, Crime",
                "8,865 Ratings"))
        tvShow.add(DataTvShow(R.drawable.poster_supergirl,
                "Supergirl (2015)",
                "Twenty-four-year-old Kara Zor-El, who was taken in by the Danvers family when she was 13 after being sent away from Krypton, must learn to embrace her powers after previously hiding them. The Danvers teach her to be careful with her powers, until she has to reveal them during an unexpected disaster, setting her on her journey of heroism.",
                "October 26, 2015",
                "42m",
                "Returning Series",
                "Action, Adventure, Drama, Science Fiction",
                "2,724 Ratings"))
        tvShow.add(DataTvShow(R.drawable.poster_supernatural,
                "Supernatural (2005)",
                "When they were boys, Sam and Dean Winchester lost their mother to a mysterious and demonic supernatural force. Subsequently, their father raised them to be soldiers. He taught them about the paranormal evil that lives in the dark corners and on the back roads of America ... and he taught them how to kill it. Now, the Winchester brothers crisscross the country in their '67 Chevy Impala, battling every kind of supernatural threat they encounter along the way.",
                "September 13, 2005",
                "45m",
                "Ended",
                "Drama, Mystery, Sci-Fi & Fantasy",
                "4,677 Ratings"))
        tvShow.add(DataTvShow(R.drawable.poster_the_simpson,
                "The Simpsons (1989)",
                "Set in Springfield, the average American town, the show focuses on the antics and everyday adventures of the Simpson family; Homer, Marge, Bart, Lisa and Maggie, as well as a virtual cast of thousands. Since the beginning, the series has been a pop culture icon, attracting hundreds of celebrities to guest star. The show has also made name for itself in its fearless satirical take on politics, media and American life in general.",
                "December 16, 1989",
                "22m",
                "Returning Series",
                "Family, Animation, Comedy, Drama",
                "5,892 Ratings"))
        tvShow.add(DataTvShow(R.drawable.poster_the_umbrella,
                "The Umbrella Academy (2019)",
                "A dysfunctional family of superheroes comes together to solve the mystery of their father's death, the threat of the apocalypse and more.",
                "February 15, 2019",
                "55m",
                "Returning Series",
                "Action & Adventure, Sci-Fi & Fantasy, Drama",
                "5,685 Ratings"))

        return tvShow
    }

    fun generateRemoteMovie(): List<MovieResponse> {
        val movie = ArrayList<MovieResponse>()

        movie.add(MovieResponse(R.drawable.poster_alita,
                "Alita: Battle Angel (2019)",
                "When Alita awakens with no memory of who she is in a future world she does not recognize, she is taken in by Ido, a compassionate doctor who realizes that somewhere in this abandoned cyborg shell is the heart and soul of a young woman with an extraordinary past.",
                "02/14/2019",
                "2h 2m",
                "Released",
                "Action, Science Fiction, Adventure",
                "6,161 Ratings"))
        movie.add(MovieResponse(R.drawable.poster_aquaman,
                "Aquaman (2018)",
                "Once home to the most advanced civilization on Earth, Atlantis is now an underwater kingdom ruled by the power-hungry King Orm. With a vast army at his disposal, Orm plans to conquer the remaining oceanic people and then the surface world. Standing in his way is Arthur Curry, Orm's half-human, half-Atlantean brother and true heir to the throne.",
                "12/21/2018",
                "2h 24m",
                "Released",
                "Action, Adventure, Fantasy",
                "9,949 Ratings"))
        movie.add(MovieResponse(R.drawable.poster_bohemian,
                "Bohemian Rhapsody (2018)",
                "Singer Freddie Mercury, guitarist Brian May, drummer Roger Taylor and bass guitarist John Deacon take the music world by storm when they form the rock 'n' roll band Queen in 1970. Hit songs become instant classics. When Mercury's increasingly wild lifestyle starts to spiral out of control, Queen soon faces its greatest challenge yet – finding a way to keep the band together amid the success and excess.",
                "11/02/2018",
                "2h 15m",
                "Released",
                "Music, Drama",
                "12,719 Ratings"))
        movie.add(MovieResponse(R.drawable.poster_creed,
                "Creed II (2018)",
                "Between personal obligations and training for his next big fight against an opponent with ties to his family's past, Adonis Creed is up against the challenge of his life.",
                "11/21/2018",
                "2h 10m",
                "Released",
                "Drama",
                "3,560 Ratings"))
        movie.add(MovieResponse(R.drawable.poster_crimes,
                "Fantastic Beasts: The Crimes of Grindelwald (2018)",
                "Gellert Grindelwald has escaped imprisonment and has begun gathering followers to his cause—elevating wizards above all non-magical beings. The only one capable of putting a stop to him is the wizard he once called his closest friend, Albus Dumbledore. However, Dumbledore will need to seek help from the wizard who had thwarted Grindelwald once before, his former student Newt Scamander, who agrees to help, unaware of the dangers that lie ahead. Lines are drawn as love and loyalty are tested, even among the truest friends and family, in an increasingly divided wizarding world.",
                "11/16/2018",
                "2h 14m",
                "Released",
                "Adventure, Fantasy, Drama",
                "7,763 Ratings"))
        movie.add(MovieResponse(R.drawable.poster_glass,
                "Glass (2019)",
                "In a series of escalating encounters, former security guard David Dunn uses his supernatural abilities to track Kevin Wendell Crumb, a disturbed man who has twenty-four personalities. Meanwhile, the shadowy presence of Elijah Price emerges as an orchestrator who holds secrets critical to both men.",
                "01/18/2019",
                "2h 9m",
                "Released",
                "Thriller, Drama, Science Fiction",
                "5,921 Ratings"))
        movie.add(MovieResponse(R.drawable.poster_how_to_train,
                "How to Train Your Dragon: The Hidden World (2019)",
                "As Hiccup fulfills his dream of creating a peaceful dragon utopia, Toothless’ discovery of an untamed, elusive mate draws the Night Fury away. When danger mounts at home and Hiccup’s reign as village chief is tested, both dragon and rider must make impossible decisions to save their kind.",
                "02/22/2019",
                "1h 44m",
                "Released",
                "Animation, Family, Adventure",
                "4,289 Ratings"))
        movie.add(MovieResponse(R.drawable.poster_infinity_war,
                "Avengers: Infinity War (2018)",
                "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.",
                "04/27/2018",
                "2h 29m",
                "Released",
                "Adventure, Action, Science Fiction",
                "20,823 Ratings"))
        movie.add(MovieResponse(R.drawable.poster_master_z,
                "Master Z: Ip Man Legacy (2018)",
                "Following his defeat by Master Ip, Cheung Tin Chi tries to make a life with his young son in Hong Kong, waiting tables at a bar that caters to expats. But it's not long before the mix of foreigners, money, and triad leaders draw him once again to the fight.",
                "12/26/2018",
                "1h 47m",
                "Released",
                "Action",
                "275 Ratings"))
        movie.add(MovieResponse(R.drawable.poster_mortal_engines,
                "Mortal Engines (2018)",
                "Many thousands of years in the future, Earth’s cities roam the globe on huge wheels, devouring each other in a struggle for ever diminishing resources. On one of these massive traction cities, the old London, Tom Natsworthy has an unexpected encounter with a mysterious young woman from the wastelands who will change the course of his life forever.",
                "12/14/2018",
                "2h 9m",
                "Released",
                "Adventure, Science Fiction",
                "3,199 Ratings"))
        movie.add(MovieResponse(R.drawable.poster_overlord,
                "Overlord (2018)",
                "France, June 1944. On the eve of D-Day, some American paratroopers fall behind enemy lines after their aircraft crashes while on a mission to destroy a radio tower in a small village near the beaches of Normandy. After reaching their target, the surviving paratroopers realise that, in addition to fighting the Nazi troops that patrol the village, they also must fight against something else.",
                "11/09/2018",
                "1h 50m",
                "Released",
                "Horror, War, Science Fiction",
                "1,935 Ratings"))
        movie.add(MovieResponse(R.drawable.poster_ralph,
                "Ralph Breaks the Internet (2018)",
                "Video game bad guy Ralph and fellow misfit Vanellope von Schweetz must risk it all by traveling to the World Wide Web in search of a replacement part to save Vanellope's video game, Sugar Rush. In way over their heads, Ralph and Vanellope rely on the citizens of the internet — the netizens — to help navigate their way, including an entrepreneur named Yesss, who is the head algorithm and the heart and soul of trend-making site BuzzzTube.",
                "11/21/2018",
                "1h 57m",
                "Released",
                "Family, Animation, Comedy, Adventure",
                "5,289 Ratings"))
        movie.add(MovieResponse(R.drawable.poster_robin_hood,
                "Robin Hood (2018)",
                "A war-hardened Crusader and his Moorish commander mount an audacious revolt against the corrupt English crown.",
                "11/21/2018",
                "1h 56m",
                "Released",
                "Adventure, Action, Thriller",
                "2,159 Ratings"))
        movie.add(MovieResponse(R.drawable.poster_spiderman,
                "Spider-Man: Into the Spider-Verse (2018)",
                "Miles Morales is juggling his life between being a high school student and being a spider-man. When Wilson \"Kingpin\" Fisk uses a super collider, others from across the Spider-Verse are transported to this dimension.",
                "12/14/2018",
                "1h 57m",
                "Released",
                "Action, Adventure, Animation, Science Fiction, Comedy",
                "8,876 Ratings"))
        movie.add(MovieResponse(R.drawable.poster_t34,
                "T-34 (2018)",
                "In 1944, a courageous group of Russian soldiers managed to escape from German captivity in a half-destroyed legendary T-34 tank. Those were the times of unforgettable bravery, fierce fighting, unbreakable love, and legendary miracles.",
                "01/01/2019",
                "2h 19m",
                "Released",
                "War, Action, Drama, History",
                "496 Ratings"))

        return movie
    }

    fun generateRemoteTvShow(): List<TvShowResponse> {
        val tvShow = ArrayList<TvShowResponse>()

        tvShow.add(TvShowResponse(R.drawable.poster_arrow,
                "Arrow (2012)",
                "Spoiled billionaire playboy Oliver Queen is missing and presumed dead when his yacht is lost at sea. He returns five years later a changed man, determined to clean up the city as a hooded vigilante armed with a bow.",
                "October 10, 2012",
                "42m",
                "Ended",
                "Crime, Drama, Mystery, Action & Adventure",
                "4,288 Ratings"))
        tvShow.add(TvShowResponse(R.drawable.poster_doom_patrol,
                "Doom Patrol (2019)",
                "The Doom Patrol’s members each suffered horrible accidents that gave them superhuman abilities — but also left them scarred and disfigured. Traumatized and downtrodden, the team found purpose through The Chief, who brought them together to investigate the weirdest phenomena in existence — and to protect Earth from what they find.",
                "February 15, 2019",
                "49m",
                "Returning Series",
                "Sci-Fi & Fantasy, Action & Adventure, Comedy",
                "747 Ratings"))
        tvShow.add(TvShowResponse(R.drawable.poster_dragon_ball,
                "Dragon Ball (1986)",
                "Long ago in the mountains, a fighting master known as Gohan discovered a strange boy whom he named Goku. Gohan raised him and trained Goku in martial arts until he died. The young and very strong boy was on his own, but easily managed. Then one day, Goku met a teenage girl named Bulma, whose search for the mystical Dragon Balls brought her to Goku's home. Together, they set off to find all seven and to grant her wish.",
                "February 26, 1986",
                "25m",
                "Ended",
                "Comedy, Sci-Fi & Fantasy, Animation, Action & Adventure",
                "1,567 Ratings"))
        tvShow.add(TvShowResponse(R.drawable.poster_family_guy,
                "Family Guy (1999)",
                "Sick, twisted, politically incorrect and Freakin' Sweet animated series featuring the adventures of the dysfunctional Griffin family. Bumbling Peter and long-suffering Lois have three kids. Stewie (a brilliant but sadistic baby bent on killing his mother and taking over the world), Meg (the oldest, and is the most unpopular girl in town) and Chris (the middle kid, he's not very bright but has a passion for movies). The final member of the family is Brian - a talking dog and much more than a pet, he keeps Stewie in check whilst sipping Martinis and sorting through his own life issues.",
                "January 31, 1999",
                "22m",
                "Returning Series",
                "Animation, Comedy",
                "2,554 Ratings"))
        tvShow.add(TvShowResponse(R.drawable.poster_flash,
                "The Flash (2014)",
                "After a particle accelerator causes a freak storm, CSI Investigator Barry Allen is struck by lightning and falls into a coma. Months later he awakens with the power of super speed, granting him the ability to move through Central City like an unseen guardian angel. Though initially excited by his newfound powers, Barry is shocked to discover he is not the only \"meta-human\" who was created in the wake of the accelerator explosion -- and not everyone is using their new powers for good. Barry partners with S.T.A.R. Labs and dedicates his life to protect the innocent. For now, only a few close friends and associates know that Barry is literally the fastest man alive, but it won't be long before the world learns what Barry Allen has become...The Flash.",
                "October 7, 2014",
                "44m",
                "Returning Series",
                "Drama, Sci-Fi & Fantasy",
                "6,611 Ratings"))
        tvShow.add(TvShowResponse(R.drawable.poster_gotham,
                "Gotham (2014)",
                "Everyone knows the name Commissioner Gordon. He is one of the crime world's greatest foes, a man whose reputation is synonymous with law and order. But what is known of Gordon's story and his rise from rookie detective to Police Commissioner? What did it take to navigate the multiple layers of corruption that secretly ruled Gotham City, the spawning ground of the world's most iconic villains? And what circumstances created them – the larger-than-life personas who would become Catwoman, The Penguin, The Riddler, Two-Face and The Joker?",
                "September 22, 2014",
                "43m",
                "Ended",
                "Drama, Fantasy, Crime",
                "2,097 Ratings"))
        tvShow.add(TvShowResponse(R.drawable.poster_grey_anatomy,
                "Grey's Anatomy (2005)",
                "Follows the personal and professional lives of a group of doctors at Seattle’s Grey Sloan Memorial Hospital.",
                "March 27, 2005",
                "43m",
                "Returning Series",
                "Drama",
                "5,080 Ratings"))
        tvShow.add(TvShowResponse(R.drawable.poster_hanna,
                "Hanna (2019)",
                "This thriller and coming-of-age drama follows the journey of an extraordinary young girl as she evades the relentless pursuit of an off-book CIA agent and tries to unearth the truth behind who she is. Based on the 2011 Joe Wright film.",
                "March 28, 2019",
                "50m",
                "Returning Series",
                "Action & Adventure, Drama",
                "423 Ratings"))
        tvShow.add(TvShowResponse(R.drawable.poster_iron_fist,
                "Marvel's Iron Fist (2017)",
                "Danny Rand resurfaces 15 years after being presumed dead. Now, with the power of the Iron Fist, he seeks to reclaim his past and fulfill his destiny.",
                "March 17, 2017",
                "55m",
                "Canceled",
                "Action & Adventure, Drama, Sci-Fi & Fantasy",
                "1,386 Ratings"))
        tvShow.add(TvShowResponse(R.drawable.poster_ncis,
                "NCIS (2003)",
                "From murder and espionage to terrorism and stolen submarines, a team of special agents investigates any crime that has a shred of evidence connected to Navy and Marine Corps personnel, regardless of rank or position.",
                "September 23, 2003",
                "45m",
                "Returning Series",
                "Crime, Action & Adventure, Drama",
                "1,341 Ratings"))
        tvShow.add(TvShowResponse(R.drawable.poster_riverdale,
                "Riverdale (2017)",
                "Set in the present, the series offers a bold, subversive take on Archie, Betty, Veronica and their friends, exploring the surreality of small-town life, the darkness and weirdness bubbling beneath Riverdale’s wholesome facade.",
                "January 26, 2017",
                "45m",
                "Returning Series",
                "Mystery, Drama, Crime",
                "8,865 Ratings"))
        tvShow.add(TvShowResponse(R.drawable.poster_supergirl,
                "Supergirl (2015)",
                "Twenty-four-year-old Kara Zor-El, who was taken in by the Danvers family when she was 13 after being sent away from Krypton, must learn to embrace her powers after previously hiding them. The Danvers teach her to be careful with her powers, until she has to reveal them during an unexpected disaster, setting her on her journey of heroism.",
                "October 26, 2015",
                "42m",
                "Returning Series",
                "Action, Adventure, Drama, Science Fiction",
                "2,724 Ratings"))
        tvShow.add(TvShowResponse(R.drawable.poster_supernatural,
                "Supernatural (2005)",
                "When they were boys, Sam and Dean Winchester lost their mother to a mysterious and demonic supernatural force. Subsequently, their father raised them to be soldiers. He taught them about the paranormal evil that lives in the dark corners and on the back roads of America ... and he taught them how to kill it. Now, the Winchester brothers crisscross the country in their '67 Chevy Impala, battling every kind of supernatural threat they encounter along the way.",
                "September 13, 2005",
                "45m",
                "Ended",
                "Drama, Mystery, Sci-Fi & Fantasy",
                "4,677 Ratings"))
        tvShow.add(TvShowResponse(R.drawable.poster_the_simpson,
                "The Simpsons (1989)",
                "Set in Springfield, the average American town, the show focuses on the antics and everyday adventures of the Simpson family; Homer, Marge, Bart, Lisa and Maggie, as well as a virtual cast of thousands. Since the beginning, the series has been a pop culture icon, attracting hundreds of celebrities to guest star. The show has also made name for itself in its fearless satirical take on politics, media and American life in general.",
                "December 16, 1989",
                "22m",
                "Returning Series",
                "Family, Animation, Comedy, Drama",
                "5,892 Ratings"))
        tvShow.add(TvShowResponse(R.drawable.poster_the_umbrella,
                "The Umbrella Academy (2019)",
                "A dysfunctional family of superheroes comes together to solve the mystery of their father's death, the threat of the apocalypse and more.",
                "February 15, 2019",
                "55m",
                "Returning Series",
                "Action & Adventure, Sci-Fi & Fantasy, Drama",
                "5,685 Ratings"))

        return tvShow
    }
}